#!/bin/bash

export PYTHONPATH=$HOME/divmod/Combinator:$PYTHONPATH

export COMBINATOR_PROJECTS=$HOME/Projects

~pypy/bin/twistd \
    --logfile ~/log/twistd.log \
    --pidfile ~/run/twistd.pid \
    --rundir ~/run/ \
    web --personal --resource-script ~/config/diffresource.rpy
